// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🔴 Red Teaming',
      items: [{ type: 'autogenerated', dirName: 'red-teaming' }],
    },
    {
      type: 'category',
      label: '🔵 Blue Teaming',
      items: [{ type: 'autogenerated', dirName: 'blue-teaming' }],
    },
    {
      type: 'category',
      label: '🛡️ GRC',
      items: [{ type: 'autogenerated', dirName: 'grc' }],
    },
    {
      type: 'category',
      label: '🌐 General Security',
      items: [{ type: 'autogenerated', dirName: 'general-security' }],
    },
    {
      type: 'category',
      label: '🎓 Certifications',
      items: [{ type: 'autogenerated', dirName: 'certifications' }],
    },
    {
      type: 'category',
      label: '🖥️ Operating Systems',
      items: [
        {
          type: 'category',
          label: 'Windows',
          items: [{ type: 'autogenerated', dirName: 'operating-systems/windows' }],
        },
        {
          type: 'category',
          label: 'Linux',
          items: [{ type: 'autogenerated', dirName: 'operating-systems/linux' }],
        },
      ],
    },
    {
      type: 'category',
      label: '🧰 Servers',
      items: [{ type: 'autogenerated', dirName: 'servers' }],
    },
    {
      type: 'category',
      label: '📡 Networking',
      items: [{ type: 'autogenerated', dirName: 'networking' }],
    },
    {
      type: 'category',
      label: '🆘 Helpdesk Basics',
      items: [{ type: 'autogenerated', dirName: 'helpdesk-basics' }],
    },
    {
      type: 'category',
      label: '🧱 Virtualization',
      items: [{ type: 'autogenerated', dirName: 'virtualization' }],
    },
  ],
};

export default sidebars;
