// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🔴 Red Teaming',
      items: ['red-teaming-overview', { type: 'autogenerated', dirName: 'red-teaming' }],
    },
    {
      type: 'category',
      label: '🔵 Blue Teaming',
      items: ['blue-teaming-overview', { type: 'autogenerated', dirName: 'blue-teaming' }],
    },
    {
      type: 'category',
      label: '🛡️ GRC',
      items: ['grc-overview', { type: 'autogenerated', dirName: 'grc' }],
    },
    {
      type: 'category',
      label: '🌐 General Security',
      items: ['general-security-overview', { type: 'autogenerated', dirName: 'general-security' }],
    },
    {
      type: 'category',
      label: '🎓 Certifications',
      items: [
        'certifications-overview',
        {
          type: 'category',
          label: 'Ethical Hacking (CEH v13)',
          items: [{ type: 'autogenerated', dirName: 'certifications/ethical-hacking' }],
        },
        'certifications/aws-certifications',
        'certifications/cisco-certifications',
        'certifications/comptia-certifications',
        'certifications/isc2-certifications',
        'certifications/microsoft-certifications',
        'certifications/practical-exam-certifications',
      ],
    },
    {
      type: 'category',
      label: '🖥️ Operating Systems',
      items: [
        'operating-systems-overview',
        {
          type: 'category',
          label: 'Windows',
          items: ['windows-overview', { type: 'autogenerated', dirName: 'operating-systems/windows' }],
        },
        {
          type: 'category',
          label: 'Linux',
          items: ['linux-overview', { type: 'autogenerated', dirName: 'operating-systems/linux' }],
        },
      ],
    },
    {
      type: 'category',
      label: '🧰 Servers',
      items: ['servers-overview', { type: 'autogenerated', dirName: 'servers' }],
    },
    {
      type: 'category',
      label: '📡 Networking',
      items: ['networking-overview', { type: 'autogenerated', dirName: 'networking' }],
    },
    {
      type: 'category',
      label: '🆘 Helpdesk Basics',
      items: ['helpdesk-basics-overview', { type: 'autogenerated', dirName: 'helpdesk-basics' }],
    },
    {
      type: 'category',
      label: '🧱 Virtualization',
      items: ['virtualization-overview', { type: 'autogenerated', dirName: 'virtualization' }],
    },
  ],
};

export default sidebars;
